services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - black-clover-network


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - black-clover-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    #  - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - postgres
      - adminer
    networks:
      - black-clover-network
volumes:
  boilerplate-db:
networks:
  black-clover-network: