export enum ENUM_SPELL_TYPE {
    COMPOUND = 'COMPOUND',
    CREATION = 'CREATION',
    CURSE = 'CURSE',
    FORBIDDEN = 'FORBIDDEN',
    HEALING = 'HEALING',
    REINCARNATION = 'REINCARNATION',
    REINFORCEMENT = 'REINFORCEMENT',
    RESTRAINING = 'RESTRAINING',
    SEAL = 'SEAL',
    TRAP = 'TRAP',
    WEAKING = 'WEAKING',
    OTHER = 'OTHER',
}

/**
 *  SPIRIT,
 *     Barrier,
    Communication,
    Compound,
    Creation,
    Curse,
    Forbidden,
    Healing,
    Reincarnation,
    Reinforcement,
    Restraining,
    Seal,
    Spirit,
    Transformation,
    Trap,
    Unite,
    Weakening,
    Melee,
    Weapon,
 */