export enum ENUM_ACTION_NAMES {
    CHANGE_CAP = 'CHANGE_CAP',
    CHANGE_ARMOR = 'CHANGE_ARMOR',
    CHANGE_LEFT_HAND = 'CHANGE_LEFT_HAND',
    CHANGE_RIGHT_HAND = 'CHANGE_RIGHT_HAND',
    CHANGE_CLOAK_ACTION = 'CHANGE_CLOAK_ACTION',
    CHANGE_GLOVES_ACTION = 'CHANGE_GLOVES_ACTION',
    CHANGE_SHOES_ACTION = 'CHANGE_SHOES_ACTION',
    CHANGE_RING_ACTION = 'CHANGE_RING_ACTION',
    CHANGE_VEHICLE_ACTION = 'CHANGE_VEHICLE_ACTION',

    BACK_TO_EQUIP_ITEM = 'back_to_equip_item',
}
