export enum SceneIds {
    entry = 'entry',
    ADMIN = 'admin-panel',
    ADD_SUPER_ADMIN = 'add-super-admin',
    ADD_ADMIN = 'add-admin',
    DELETE_ADMIN = 'delete-admin',

    ARMY_REQUEST_ACCEPT = 'army-request-accept',
    ARMY_REQUEST_REJECT = 'army-request-reject',
    createCharacter = 'create-character',
    createSpell = 'create-spell',
    createSpells = 'create-spells',
    equipment = 'equipment',
    help = 'help',
    quests = 'quests',
    roll = 'foll',
    about = 'about',
    home = 'home',
    profile = 'profile',

    spells = 'spells',
    inventory = 'inventory',
    wallet = 'wallet',
    work = 'work',
    bio = 'bio',
    characterParameters = 'character-parameters',
    mySpirits = 'my-spirits',
    allSpirits = 'all-spirits',
    allDevils = 'all-devils',
    allDevilsByRank = 'all-devils-by-rank',
    allDevilsByFloor = 'all-devils-by-floor',
    myDevils = 'my-devils',
    map = 'map',
    mines = 'mines',
    editCharacterName = 'edit-character-name',

    organizations = 'organizations',
    church = 'church',
    armedForces = 'armedForces',
    createSquad = 'createSquad',
    magicParlament = 'magicParlament',
    createRequestToParlament = 'create-request-to-parlament',
    //grimore
    //edit
    grimoire = 'grimoire',
    grimoireAdd = 'grimoire-add',
    grimoireEditMagicName = 'grimoire-edit-magic-name',
    grimoireEditMagicColor = 'grimoire-edit-magic-color',
    REQUEST_TO_PARLAMENT = 'REQUEST_TO_PARLAMENT',
}
