import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1719160028542 implements MigrationInterface {
    name = ' $npmConfigName1719160028542'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "toy_shop_address_entity" ("id" SERIAL NOT NULL, "address" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86ec7bc8ba56f7ac7e2f3371327" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "toy_shop_entity" ("id" SERIAL NOT NULL, "shopName" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "addressId" integer, CONSTRAINT "REL_bced0fab98307df5ba79db4b34" UNIQUE ("addressId"), CONSTRAINT "PK_d15d3e671c3d0779df91d550a64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cat_toy_entity" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "shopId" integer, "catId" integer, "sizeHeight" integer NOT NULL, "sizeWidth" integer NOT NULL, "sizeLength" integer NOT NULL, CONSTRAINT "PK_ac5c1672d60b151112f65ebcf09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cat" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "color" character varying NOT NULL, "age" integer, "cutenessLevel" text NOT NULL, "lastVetVisit" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "homeId" integer, "sizeHeight" integer NOT NULL, "sizeWidth" integer NOT NULL, "sizeLength" integer NOT NULL, CONSTRAINT "REL_97f120ed85f1eca4908bc4543c" UNIQUE ("homeId"), CONSTRAINT "PK_7704d5c2c0250e4256935ae31b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cat_home_pillow_entity" ("id" SERIAL NOT NULL, "color" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "homeId" integer, CONSTRAINT "PK_f662a91a08584ba090799375a1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cat_home_entity" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6bdfe5785861b7dad300f8f0ec0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cat_hair_entity" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "colors" text array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ebf2312d25abd1cddb71aa02a69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "burg" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "image" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "provinceId" uuid, CONSTRAINT "PK_3f599743b5ef43b82430448c756" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "province_form" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7100060d132705fe129ff576026" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "province" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "short_name" character varying NOT NULL, "full_name" character varying NOT NULL, "image" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "state_id" uuid, "form_id" uuid, CONSTRAINT "PK_4f461cb46f57e806516b7073659" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stateform" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8a14859db916aeda81c38a99b15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "money" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "copper" integer NOT NULL, "silver" integer NOT NULL, "eclevtrum" integer NOT NULL, "gold" integer NOT NULL, "platinum" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_532685f389ab66b70115668bf09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "armed_forces_rank" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "forces_id" uuid NOT NULL, "nsleft" integer NOT NULL DEFAULT '1', "nsright" integer NOT NULL DEFAULT '2', "parentId" uuid, "salary_id" uuid, CONSTRAINT "REL_49f6578e9d32e203ff8bdbeba1" UNIQUE ("salary_id"), CONSTRAINT "PK_4409e1b5d5322304affaafbbed0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "armed_forces_permission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "leader" character varying NOT NULL, "captain" character varying NOT NULL, "viceCapitan" character varying NOT NULL, "member" character varying NOT NULL, "warehouse" character varying NOT NULL, "inventory" character varying NOT NULL, "garage" character varying NOT NULL, "workshop" character varying NOT NULL, CONSTRAINT "PK_af4bab6db4779d6f66e4307f8d3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "armed_forces_job" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "permissions_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_7950c11cbb3dc71f364fc69144" UNIQUE ("permissions_id"), CONSTRAINT "PK_9f4a32de28c890832b37fee9cc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "armed_forces_member" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "character_id" uuid NOT NULL, "armed_forces_id" uuid NOT NULL, "rank_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "job_title_id" uuid, CONSTRAINT "REL_cc2cf86f1190c133290a824d70" UNIQUE ("character_id"), CONSTRAINT "PK_576b7574a9a23fdac1dc45c9d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "squad_member" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "armed_forces_member_id" uuid, "squad_id" uuid, CONSTRAINT "REL_6dceec6ada0c6475b462b9fac2" UNIQUE ("armed_forces_member_id"), CONSTRAINT "PK_eef2770b0e48d54d4169bb2f6bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "squad_postitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "squad_id" uuid, "captain" uuid, "vice_captain" uuid, CONSTRAINT "REL_231556cd2d6d9e74640d7a635f" UNIQUE ("squad_id"), CONSTRAINT "REL_b77c861cd7007de6f9a9cafb7f" UNIQUE ("captain"), CONSTRAINT "REL_99c3c43a3481a22d94d21a6af0" UNIQUE ("vice_captain"), CONSTRAINT "PK_22ca43fd6eb05f3d79d090849c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "squads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "image" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "forces_id" uuid, CONSTRAINT "PK_6ef0717a3dbb0f326bc387dfacb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."armed_forces_request_status_enum" AS ENUM('accepted', 'pending', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "armed_forces_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "forces_id" uuid NOT NULL, "tg_username" character varying NOT NULL, "tg_user_id" character varying NOT NULL, "character_id" uuid NOT NULL, "status" "public"."armed_forces_request_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a26e457bf6f666ac72819ae1601" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "armer_forces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "descripiton" character varying NOT NULL, "state_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_7cba12869189b72b04204c4f74" UNIQUE ("state_id"), CONSTRAINT "PK_abd1de313e716a3ce7c608f12d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "state" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "fullName" character varying NOT NULL, "description" character varying NOT NULL, "symbol" character varying NOT NULL, "image" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "form_id" uuid, CONSTRAINT "PK_549ffd046ebab1336c3a8030a12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "race" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "bonus_hp" integer NOT NULL, "bonus_magic_power" integer NOT NULL, "natural_mana" boolean NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3068b184130d87a20e516045bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "background" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "age" integer NOT NULL, "sex" character varying NOT NULL, "history" character varying NOT NULL, "hobbies" character varying, "goals" character varying, "worldview" character varying, "characterTraits" character varying, "ideals" character varying, "attachments" character varying, "weaknesses" character varying, "quotes" character varying array, "appearance" character varying NOT NULL, "race_id" uuid NOT NULL, "state_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7271b4d2e4bd0f68b3fdb5c090a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ability" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "score" integer NOT NULL, "modifier" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5643559d435d01ec126981417a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "armor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "armorType" character varying NOT NULL, "cost" character varying NOT NULL, "ac_base" integer NOT NULL, "ac_bonus" integer NOT NULL, "stealthDisadvantage" boolean NOT NULL, "weight" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9897d8f2edafda53ca0412ddeec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "armor_class" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "base" integer NOT NULL, "bonus" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5ba1e32999f6b0ce7c57665e4da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "speed" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "base" integer NOT NULL, "bonus" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "character_characteristics_id" uuid, CONSTRAINT "PK_3725257a5ff7a71c525874d4444" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proficiency" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" integer NOT NULL, "extraBonus" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5d1139f6dd3f59ad11b90b5fc57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "сharacter_сharacteristics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "experience" integer NOT NULL, "current_level" integer NOT NULL, "max_level" integer NOT NULL, "currentHealth" integer NOT NULL, "maxHealth" integer NOT NULL, "magic_power" integer NOT NULL, "hunger" integer NOT NULL, "sanity" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "proficiency_id" uuid, "strength_id" uuid, "dexterity_id" uuid, "constitution_id" uuid, "intelligence_id" uuid, "wisdom_id" uuid, "charisma_id" uuid, "armor_class_id" uuid, CONSTRAINT "REL_3de7660ddbb03266bf3b45f46b" UNIQUE ("proficiency_id"), CONSTRAINT "REL_a33571e93e431bf7954a725810" UNIQUE ("strength_id"), CONSTRAINT "REL_2266566630597e725171d7d149" UNIQUE ("dexterity_id"), CONSTRAINT "REL_20cdb54b7dc2dfc3b1608d9272" UNIQUE ("constitution_id"), CONSTRAINT "REL_bec0cf5cc8f25e02155802a1ff" UNIQUE ("intelligence_id"), CONSTRAINT "REL_3ff92766c0608a72fad9bcd4fc" UNIQUE ("wisdom_id"), CONSTRAINT "REL_e755b69e23f6f408b4dd3a8c16" UNIQUE ("charisma_id"), CONSTRAINT "REL_d60a5a2c749df61c88346e6096" UNIQUE ("armor_class_id"), CONSTRAINT "PK_9ecdbc6923171be1ee71bca3ea2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "spell_requirements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "minimalLevel" integer NOT NULL, "magic_atribbutes" text array NOT NULL, CONSTRAINT "PK_e46b14dba921885159dfca2671b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."spell_type_enum" AS ENUM('COMPOUND', 'CREATION', 'CURSE', 'FORBIDDEN', 'HEALING', 'REINCARNATION', 'REINFORCEMENT', 'RESTRAINING', 'SEAL', 'TRAP', 'WEAKING', 'DEVIL_UNION', 'SPIRIT_UNION', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."spell_status_enum" AS ENUM('DRAFT', 'NOT_APPROVED', 'APPROVED')`);
        await queryRunner.query(`CREATE TABLE "spell" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "damage" integer NOT NULL, "range" character varying NOT NULL, "duration" character varying NOT NULL, "cost" integer NOT NULL, "cast_type" character varying NOT NULL, "cooldown" character varying NOT NULL, "type" "public"."spell_type_enum" NOT NULL DEFAULT 'CREATION', "goals" character varying NOT NULL, "requirements_id" uuid NOT NULL, "status" "public"."spell_status_enum" NOT NULL DEFAULT 'DRAFT', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "grimoire_id" character varying NOT NULL, "gromoire_id" uuid, CONSTRAINT "REL_e46b14dba921885159dfca2671" UNIQUE ("requirements_id"), CONSTRAINT "PK_148c7e69812f7047fe34e3848fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."grimoire_status_enum" AS ENUM('NOT_APPROVED', 'APPROVED')`);
        await queryRunner.query(`CREATE TABLE "grimoire" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "magicName" character varying NOT NULL, "status" "public"."grimoire_status_enum" NOT NULL DEFAULT 'NOT_APPROVED', "cover_image_url" character varying, "coverSymbol" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_adacd671c000d938874ad610c8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "note" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying NOT NULL, "date" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "character_id" uuid, CONSTRAINT "PK_96d0c172a4fba276b1bbed43058" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallet" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "copper" integer NOT NULL, "silver" integer NOT NULL, "electrum" integer NOT NULL, "gold" integer NOT NULL, "platinum" integer NOT NULL, "use_platinum" boolean NOT NULL, "useElectrum" boolean NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bec464dd8d54c39c54fd32e2334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "faction_rank" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "salary" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b79fa34c30029ac9ad35780bd44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gang_zone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "faction_id" uuid, CONSTRAINT "REL_a2816f8d6dbb4c761d7817dcba" UNIQUE ("faction_id"), CONSTRAINT "PK_99b383d5d831b73753279ea55c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "faction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "money" integer NOT NULL, "materials" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5935637aa4ecd999ac0555ae5a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "faction_member" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "charachter_id" uuid, "faction_id" uuid, "rank_id" uuid, CONSTRAINT "REL_6cc8b2ec024082d725ab16304d" UNIQUE ("charachter_id"), CONSTRAINT "PK_eb26bd93443aab6639421f0e911" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "court_worker" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "character_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "problemsId" uuid, CONSTRAINT "REL_9073282223b204c83ec2393dbb" UNIQUE ("character_id"), CONSTRAINT "PK_74ccf7d4dd32c906e66e6c6698b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "submission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isPublic" boolean NOT NULL, "submitTime" TIMESTAMP NOT NULL, "content" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7faa571d0e4a7076e85890c9bd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe96352b2f1e9bfb922c54eba1" ON "submission" ("isPublic") `);
        await queryRunner.query(`CREATE INDEX "IDX_ebd1b63340ac17250257bb42d3" ON "submission" ("submitTime") `);
        await queryRunner.query(`CREATE TYPE "public"."problem_status_enum" AS ENUM('DRAFT', 'PENDING', 'UNDER_CONSIDERATION', 'SOLVED')`);
        await queryRunner.query(`CREATE TABLE "problem" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "displayId" SERIAL NOT NULL, "isPublic" boolean NOT NULL, "creator_id" uuid NOT NULL, "status" "public"."problem_status_enum" NOT NULL DEFAULT 'DRAFT', "content" character varying NOT NULL, "submission_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "court_worker_id" uuid, CONSTRAINT "REL_9c6e6c677067c6898b0a376358" UNIQUE ("submission_id"), CONSTRAINT "PK_119b5ca6f3371465bf1f0f90219" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_219b1e601b8b47e38de7f91dbe" ON "problem" ("displayId") `);
        await queryRunner.query(`CREATE TABLE "plant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "emoji_icon" character varying NOT NULL, "description" character varying NOT NULL, "watering_interval" integer NOT NULL, "sale_price" integer NOT NULL, "death_time" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "price_id" uuid, CONSTRAINT "REL_de6102dd5f4419b65607802ae8" UNIQUE ("price_id"), CONSTRAINT "PK_97e1eb0d045aadea59401ece5ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pot" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rentedUntil" TIMESTAMP, "liveUntil" TIMESTAMP, "nextWatering" TIMESTAMP, "stage" integer NOT NULL DEFAULT '0', "plant_id" uuid, CONSTRAINT "PK_6ef954b600e6ef1baf00a8002f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "garden" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pot_1" uuid NOT NULL, "pot_2" uuid NOT NULL, "pot_3" uuid NOT NULL, "pot_4" uuid NOT NULL, "pot_5" uuid NOT NULL, CONSTRAINT "REL_d2d6f65a602399f8c176dd4b61" UNIQUE ("pot_1"), CONSTRAINT "REL_a9c52f99fd00fcb0522fa4e272" UNIQUE ("pot_2"), CONSTRAINT "REL_525a4a026064dd97d6c6771c3e" UNIQUE ("pot_3"), CONSTRAINT "REL_228e040a77b3ef25e8cc6ca69c" UNIQUE ("pot_4"), CONSTRAINT "REL_b065c7e8306df54e5d68f7a489" UNIQUE ("pot_5"), CONSTRAINT "PK_d08af92b4c172606e5372364553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "toolKit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "kit" character varying NOT NULL, "cost" character varying NOT NULL, "weight" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_96b9d5a2e4c820007e0eaaf4954" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "govNumber" character varying NOT NULL, "fuel" integer NOT NULL, "state" integer NOT NULL, "tuning" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_187fa17ba39d367e5604b3d1ec9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gear" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "itemType" character varying NOT NULL, "quantity" integer NOT NULL, "cost" character varying NOT NULL, "weight" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f57e90b5a9b1363699e02ffe30c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drink_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8f73079073c0659509a6c455ae7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drink" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "appearance" character varying NOT NULL, "quality" integer NOT NULL, "strength" integer NOT NULL, "drink_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "price_id" uuid, CONSTRAINT "REL_3005223ba91709f26b9e6e347a" UNIQUE ("price_id"), CONSTRAINT "PK_d2bcca4059e927221cce0f95756" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_category" ("id" SERIAL NOT NULL, "parentId" integer, "name" character varying(30) NOT NULL, "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3776df63b26aee9f2089a70403d" UNIQUE ("name"), CONSTRAINT "PK_91ba90f150e8804bdaad7b17ff8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."equpment_item_rarity_enum" AS ENUM('0', '1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TYPE "public"."equpment_item_bodypart_enum" AS ENUM('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11')`);
        await queryRunner.query(`CREATE TABLE "equpment_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(30) NOT NULL, "description" text NOT NULL, "image" character varying(40), "category_id" character varying NOT NULL, "rarity" "public"."equpment_item_rarity_enum" NOT NULL DEFAULT '0', "bodyPart" "public"."equpment_item_bodypart_enum" NOT NULL DEFAULT '11', "heal" integer NOT NULL DEFAULT '0', "strength" integer NOT NULL DEFAULT '0', "dexterity" integer NOT NULL DEFAULT '0', "vitality" integer NOT NULL DEFAULT '0', "intellect" integer NOT NULL DEFAULT '0', "luck" integer NOT NULL DEFAULT '0', "criticalChance" integer NOT NULL DEFAULT '0', "criticalDamage" integer NOT NULL DEFAULT '0', "dodgeChance" integer NOT NULL DEFAULT '0', "map_health" integer NOT NULL DEFAULT '0', "max_magic_power" integer NOT NULL DEFAULT '0', "armor" integer NOT NULL DEFAULT '0', "physical_attack_damage" integer NOT NULL DEFAULT '0', "magic_attack_damage" integer NOT NULL DEFAULT '0', "inventory_pace" integer NOT NULL DEFAULT '0', "physical_defense" integer NOT NULL DEFAULT '0', "magic_defense" integer NOT NULL DEFAULT '0', "accuracy_rate" integer NOT NULL DEFAULT '0', "evasion" integer NOT NULL DEFAULT '0', "craft" integer NOT NULL DEFAULT '0', "speed" integer NOT NULL DEFAULT '0', "jump" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "caterogry_id" integer, CONSTRAINT "UQ_56a8fc1acb904dc72862ae64c8d" UNIQUE ("name"), CONSTRAINT "PK_3bf00a711bd61f2beee9c044139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equipment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "armor_id" uuid, "cloak_id" uuid, "left_hand_id" uuid, "right_hand_id" uuid, "gloves_id" uuid, "shoes_id" uuid, "ring_id" uuid, "vehicle_id" uuid, CONSTRAINT "PK_0722e1b9d6eb19f5874c1678740" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."character_type_enum" AS ENUM('NPC', 'PC')`);
        await queryRunner.query(`CREATE TABLE "character" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "avatar" character varying, "type" "public"."character_type_enum" NOT NULL DEFAULT 'PC', "prodigy" boolean NOT NULL, "background_id" uuid NOT NULL, "characteristics_id" uuid NOT NULL, "grimoire_id" uuid, "inventory_id" uuid NOT NULL, "equipment_id" uuid NOT NULL, "wallet_id" uuid NOT NULL, "user_id" uuid NOT NULL, "gargen_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "garden_id" uuid, CONSTRAINT "REL_55d96be2679a079fb92a8c3238" UNIQUE ("background_id"), CONSTRAINT "REL_70fabaf90fc01eea3796b9b3ce" UNIQUE ("characteristics_id"), CONSTRAINT "REL_0d02288a8b2bc07298f21af0a5" UNIQUE ("grimoire_id"), CONSTRAINT "REL_523d22374b8851fe6e1a3c574c" UNIQUE ("inventory_id"), CONSTRAINT "REL_4afeeea248417ce2474b06820d" UNIQUE ("equipment_id"), CONSTRAINT "REL_3c72e1541fe3bb8c837daa7ecf" UNIQUE ("wallet_id"), CONSTRAINT "REL_213c1fb65c9f528cc11393f2ed" UNIQUE ("user_id"), CONSTRAINT "REL_aa0421a683f4459e9ed104fa97" UNIQUE ("garden_id"), CONSTRAINT "PK_6c4aec48c564968be15078b8ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."game_user_type_enum" AS ENUM('OWNER', 'ADMIN', 'OPRDINARY')`);
        await queryRunner.query(`CREATE TABLE "game_user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tg_user_id" character varying NOT NULL, "type" "public"."game_user_type_enum" NOT NULL DEFAULT 'OPRDINARY', CONSTRAINT "PK_0744ead8ea37cf3325c971f5f18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "spirit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "image_path" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a295b8aa6fbc92f4b5100dc5fbb" UNIQUE ("name"), CONSTRAINT "PK_35de1b05bb7d605904f73cac2ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank_account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "copper" integer NOT NULL, "silver" integer NOT NULL, "eclevtrum" integer NOT NULL, "gold" integer NOT NULL, "platinum" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "bank_id" uuid, CONSTRAINT "PK_f3246deb6b79123482c6adb9745" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7651eaf705126155142947926e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "money_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender" character varying NOT NULL, "recipient" character varying NOT NULL, "copper" integer NOT NULL, "silver" integer NOT NULL, "electrum" integer NOT NULL, "gold" integer NOT NULL, "platinum" integer NOT NULL, "note" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6ae5afcfa00a6a164c9237fb78a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mineral" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "image" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7163ddfaca3b9fc68b150c662cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mine" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_200c63ca703bb95d74c475867b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wanted" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creator" character varying NOT NULL, "suspect" character varying NOT NULL, "priority" integer NOT NULL, "reason" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f95ffdcbd385c61a73504a5d4ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "problem_judge_info" ("problemId" uuid NOT NULL, "judgeInfo" json NOT NULL, "submittable" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86e8539b96ed22ce70416416b1e" PRIMARY KEY ("problemId"))`);
        await queryRunner.query(`CREATE TABLE "arrest" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "time" TIMESTAMP NOT NULL, "reason" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8b8dfe811c16994b221e02b1e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "weapons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "weaponType" character varying NOT NULL, "cost" character varying NOT NULL, "damage" character varying NOT NULL, "damageType" character varying NOT NULL, "weight" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a102f55ffbab023a922ac10ab76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shop" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "item_id" uuid NOT NULL, "is_active" boolean NOT NULL, CONSTRAINT "REL_45ef796043f3b27975c32d94d2" UNIQUE ("item_id"), CONSTRAINT "PK_ad47b7c6121fe31cb4b05438e44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "necklace_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_408ee31ba3716845788dbdf0759" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ring_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c7d3dc232d283fe3f83082ccc46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schield_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a314c4d56268490c5179ff7eb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "market" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_id" uuid NOT NULL, "price" integer NOT NULL, "item_id" uuid NOT NULL, CONSTRAINT "REL_459d9cecb1ca31461755460b4c" UNIQUE ("owner_id"), CONSTRAINT "REL_fc9f91dbb8a0d0675d00d29247" UNIQUE ("item_id"), CONSTRAINT "PK_1e9a2963edfd331d92018e3abac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "house" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "locked" boolean NOT NULL, "paid" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8c9220195fd0a289745855fe908" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "helmet_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f86eae8e4aa5323df9887bcd200" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clothes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "gender" character varying NOT NULL, "category" character varying NOT NULL, "style" integer NOT NULL, "price" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c73aa6c72fd4b3213bfcdc8739b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cloak_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d8706d2015f8a255d2f40b287f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "boots_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d79b6865db9985ef37758bb14b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accessory_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_97f87eb19415d6425c8f99405a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mana_zone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "level" integer NOT NULL, CONSTRAINT "PK_236a9ceb89f2b794bc9cba5ea44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mana_skin" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c38423db44ebc5b31d56dab5c4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grimoire_worker" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "character_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_118a283f4407541e0f68e31e75" UNIQUE ("character_id"), CONSTRAINT "PK_f8c71ce3f7ae6a5676e87278502" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grimoire_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "magic_name" character varying NOT NULL, "tg_username" character varying NOT NULL, "tg_user_id" character varying NOT NULL, CONSTRAINT "PK_6273721f77dced7fe447d79aaf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."announcement_type_enum" AS ENUM('0', '1', '2')`);
        await queryRunner.query(`CREATE TABLE "announcement" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying NOT NULL, "type" "public"."announcement_type_enum" NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e0ef0550174fd1099a308fd18a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "devil_spell" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "range" character varying NOT NULL, "duration" character varying NOT NULL, "cost" character varying NOT NULL, "castTime" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6ebb0679e6097c8d92b090c865f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."devils_floor_enum" AS ENUM('1', '2', '3', '4', '5', '6', '7')`);
        await queryRunner.query(`CREATE TYPE "public"."devils_rank_enum" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "devils" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL, "image_path" character varying NOT NULL, "floor" "public"."devils_floor_enum" NOT NULL DEFAULT '1', "rank" "public"."devils_rank_enum" NOT NULL DEFAULT '4', "magic_type" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_04512b7bd53e672da912d69dc13" UNIQUE ("name"), CONSTRAINT "PK_a5fe548e4adfa079304fe67f027" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."devil_union_maxavailablepercent_enum" AS ENUM('10', '25', '50', '65', '80', '100')`);
        await queryRunner.query(`CREATE TYPE "public"."devil_union_currentpercent_enum" AS ENUM('10', '25', '50', '65', '80', '100')`);
        await queryRunner.query(`CREATE TABLE "devil_union" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "maxAvailablePercent" "public"."devil_union_maxavailablepercent_enum" NOT NULL DEFAULT '10', "currentPercent" "public"."devil_union_currentpercent_enum" NOT NULL DEFAULT '10', "devil_id" uuid NOT NULL, "character_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_52aec65a8a2bd6aaa314b489a2" UNIQUE ("devil_id"), CONSTRAINT "REL_ea32ff921afa217b45f7ade20f" UNIQUE ("character_id"), CONSTRAINT "PK_48eb6c40d4d8e7c37f0dd9ecd0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."devil_default_spells_percent_enum" AS ENUM('10', '25', '50', '65', '80', '100')`);
        await queryRunner.query(`CREATE TABLE "devil_default_spells" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "percent" "public"."devil_default_spells_percent_enum" NOT NULL DEFAULT '10', "character_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "devil_id" uuid, "spell_id" uuid, CONSTRAINT "REL_929c58456251556b2095ff58d9" UNIQUE ("devil_id"), CONSTRAINT "REL_d6a340361d8857cbf4ba12e2f3" UNIQUE ("spell_id"), CONSTRAINT "PK_703b08afcf76a2a174c450d4a93" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "food_component" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "flavors" character varying array NOT NULL, "textures" character varying array NOT NULL, "colors" character varying array NOT NULL, "category" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_10bc7339644d0df09320b7c80e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."skill_skillproficiency_enum" AS ENUM('0', '0.5', '1', '2')`);
        await queryRunner.query(`CREATE TABLE "skill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "skillProficiency" "public"."skill_skillproficiency_enum" NOT NULL DEFAULT '1', "extraBonus" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "ability_id" uuid, "proficiency_id" uuid, CONSTRAINT "REL_050ba8921bff2965456d92b2ce" UNIQUE ("ability_id"), CONSTRAINT "REL_0e6b09300470b12bdaa2dc5337" UNIQUE ("proficiency_id"), CONSTRAINT "PK_a0d33334424e64fb78dc3ce7196" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "passive_skill" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "base" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "skill_id" uuid, CONSTRAINT "REL_b1ff57d98655574c868bdf823d" UNIQUE ("skill_id"), CONSTRAINT "PK_41d6f2f8d977cefe37fd00bd3da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cat_friends_cat" ("catId_1" integer NOT NULL, "catId_2" integer NOT NULL, CONSTRAINT "PK_7575f3788dff6b5182f0fd11355" PRIMARY KEY ("catId_1", "catId_2"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba407ac9e21d01a6ba443c27d6" ON "cat_friends_cat" ("catId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_467ed799a40f2b816bf6a8f524" ON "cat_friends_cat" ("catId_2") `);
        await queryRunner.query(`CREATE TABLE "inventory_eqipment_items" ("inventoryId" uuid NOT NULL, "equpmentItemId" uuid NOT NULL, CONSTRAINT "PK_e803dcc43e8507cee9bf498b10e" PRIMARY KEY ("inventoryId", "equpmentItemId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c5cb420e037ea92202f6035d29" ON "inventory_eqipment_items" ("inventoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e64ac9b2a96181f165282cba41" ON "inventory_eqipment_items" ("equpmentItemId") `);
        await queryRunner.query(`CREATE TABLE "inventory_drinks" ("inventoryId" uuid NOT NULL, "drinkId" uuid NOT NULL, CONSTRAINT "PK_a21b76e99b36abebb3ca90c6e38" PRIMARY KEY ("inventoryId", "drinkId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_668ae9dbce0ac1d5e4600571ec" ON "inventory_drinks" ("inventoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_92faac90704a9f121d856bf5b7" ON "inventory_drinks" ("drinkId") `);
        await queryRunner.query(`CREATE TABLE "intentory_toolkit" ("inventoryId" uuid NOT NULL, "toolKitId" uuid NOT NULL, CONSTRAINT "PK_4ce46f813650f627e92811f1002" PRIMARY KEY ("inventoryId", "toolKitId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b1362fffb9935858d2a66ff0d" ON "intentory_toolkit" ("inventoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef48b38b9220433b6973d9da71" ON "intentory_toolkit" ("toolKitId") `);
        await queryRunner.query(`CREATE TABLE "inventory_gears" ("inventoryId" uuid NOT NULL, "gearId" uuid NOT NULL, CONSTRAINT "PK_5a93328bef76cd0a11a739f6080" PRIMARY KEY ("inventoryId", "gearId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54d776e18dc8ee012d50c7eedf" ON "inventory_gears" ("inventoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_50175581d42a794ce4b6d3a21e" ON "inventory_gears" ("gearId") `);
        await queryRunner.query(`CREATE TABLE "inventory_vehicles" ("inventoryId" uuid NOT NULL, "vehicleId" uuid NOT NULL, CONSTRAINT "PK_6d4ca23f3ae9a567771e51a1a7f" PRIMARY KEY ("inventoryId", "vehicleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a55065581d1648dc7aad273409" ON "inventory_vehicles" ("inventoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5f68ebe32de2fbb7cb0ebc1e7" ON "inventory_vehicles" ("vehicleId") `);
        await queryRunner.query(`ALTER TABLE "toy_shop_entity" ADD CONSTRAINT "FK_bced0fab98307df5ba79db4b34a" FOREIGN KEY ("addressId") REFERENCES "toy_shop_address_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cat_toy_entity" ADD CONSTRAINT "FK_d8f463fc68814dfd051a9680361" FOREIGN KEY ("shopId") REFERENCES "toy_shop_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cat_toy_entity" ADD CONSTRAINT "FK_441e45eec97723bb12d5123213a" FOREIGN KEY ("catId") REFERENCES "cat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cat" ADD CONSTRAINT "FK_97f120ed85f1eca4908bc4543c6" FOREIGN KEY ("homeId") REFERENCES "cat_home_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cat_home_pillow_entity" ADD CONSTRAINT "FK_62cf9d1690964fb54245eba4872" FOREIGN KEY ("homeId") REFERENCES "cat_home_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "burg" ADD CONSTRAINT "FK_d51177135257fdd6c86a4262104" FOREIGN KEY ("provinceId") REFERENCES "province"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "province" ADD CONSTRAINT "FK_51b3ecc6d0fd9eb342ee8742274" FOREIGN KEY ("state_id") REFERENCES "state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "province" ADD CONSTRAINT "FK_7100060d132705fe129ff576026" FOREIGN KEY ("form_id") REFERENCES "province_form"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_rank" ADD CONSTRAINT "FK_888b47b15df118f71e419c68419" FOREIGN KEY ("parentId") REFERENCES "armed_forces_rank"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_rank" ADD CONSTRAINT "FK_49f6578e9d32e203ff8bdbeba17" FOREIGN KEY ("salary_id") REFERENCES "money"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_rank" ADD CONSTRAINT "FK_775d68267d8bddf6a43dc2f9527" FOREIGN KEY ("forces_id") REFERENCES "armer_forces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_job" ADD CONSTRAINT "FK_7950c11cbb3dc71f364fc69144a" FOREIGN KEY ("permissions_id") REFERENCES "armed_forces_permission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_member" ADD CONSTRAINT "FK_cc2cf86f1190c133290a824d70c" FOREIGN KEY ("character_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_member" ADD CONSTRAINT "FK_92f902273784e2eb77cb64a70f5" FOREIGN KEY ("armed_forces_id") REFERENCES "armer_forces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_member" ADD CONSTRAINT "FK_6ec70ac1d854909296159b38efb" FOREIGN KEY ("rank_id") REFERENCES "armed_forces_rank"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_member" ADD CONSTRAINT "FK_039f9946eb75f071be7fc30e24f" FOREIGN KEY ("job_title_id") REFERENCES "armed_forces_job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "squad_member" ADD CONSTRAINT "FK_6dceec6ada0c6475b462b9fac2a" FOREIGN KEY ("armed_forces_member_id") REFERENCES "armed_forces_member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "squad_member" ADD CONSTRAINT "FK_e9cfaaedfe354d73610ffa47f07" FOREIGN KEY ("squad_id") REFERENCES "squads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "squad_postitions" ADD CONSTRAINT "FK_231556cd2d6d9e74640d7a635f4" FOREIGN KEY ("squad_id") REFERENCES "squads"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "squad_postitions" ADD CONSTRAINT "FK_b77c861cd7007de6f9a9cafb7f1" FOREIGN KEY ("captain") REFERENCES "squad_member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "squad_postitions" ADD CONSTRAINT "FK_99c3c43a3481a22d94d21a6af0d" FOREIGN KEY ("vice_captain") REFERENCES "squad_member"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "squads" ADD CONSTRAINT "FK_b6692363007ff4724ef82dd1fbf" FOREIGN KEY ("forces_id") REFERENCES "armer_forces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_request" ADD CONSTRAINT "FK_0d66a57cc15bb9ac71b799646eb" FOREIGN KEY ("forces_id") REFERENCES "armer_forces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armed_forces_request" ADD CONSTRAINT "FK_a26eb5106444922468f2c4c4470" FOREIGN KEY ("character_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "armer_forces" ADD CONSTRAINT "FK_7cba12869189b72b04204c4f741" FOREIGN KEY ("state_id") REFERENCES "state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "state" ADD CONSTRAINT "FK_9e79bcb4b9c77c2862cffc0eb10" FOREIGN KEY ("form_id") REFERENCES "stateform"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "background" ADD CONSTRAINT "FK_5d6f6589e1b7d72329c7810f39c" FOREIGN KEY ("race_id") REFERENCES "race"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "background" ADD CONSTRAINT "FK_65d9c4a0ed73462a9f923546192" FOREIGN KEY ("state_id") REFERENCES "state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speed" ADD CONSTRAINT "FK_91b47d4fcf2aa79c2032c8059f8" FOREIGN KEY ("character_characteristics_id") REFERENCES "сharacter_сharacteristics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" ADD CONSTRAINT "FK_3de7660ddbb03266bf3b45f46bb" FOREIGN KEY ("proficiency_id") REFERENCES "proficiency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" ADD CONSTRAINT "FK_a33571e93e431bf7954a7258103" FOREIGN KEY ("strength_id") REFERENCES "ability"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" ADD CONSTRAINT "FK_2266566630597e725171d7d1490" FOREIGN KEY ("dexterity_id") REFERENCES "ability"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" ADD CONSTRAINT "FK_20cdb54b7dc2dfc3b1608d92729" FOREIGN KEY ("constitution_id") REFERENCES "ability"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" ADD CONSTRAINT "FK_bec0cf5cc8f25e02155802a1ff6" FOREIGN KEY ("intelligence_id") REFERENCES "ability"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" ADD CONSTRAINT "FK_3ff92766c0608a72fad9bcd4fc2" FOREIGN KEY ("wisdom_id") REFERENCES "ability"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" ADD CONSTRAINT "FK_e755b69e23f6f408b4dd3a8c162" FOREIGN KEY ("charisma_id") REFERENCES "ability"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" ADD CONSTRAINT "FK_d60a5a2c749df61c88346e60968" FOREIGN KEY ("armor_class_id") REFERENCES "armor_class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell" ADD CONSTRAINT "FK_e46b14dba921885159dfca2671b" FOREIGN KEY ("requirements_id") REFERENCES "spell_requirements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell" ADD CONSTRAINT "FK_1e2393cb4b4223f42e4e91d91dc" FOREIGN KEY ("gromoire_id") REFERENCES "grimoire"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "note" ADD CONSTRAINT "FK_9784437ac65ceb4557307cfdc8a" FOREIGN KEY ("character_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gang_zone" ADD CONSTRAINT "FK_a2816f8d6dbb4c761d7817dcbaa" FOREIGN KEY ("faction_id") REFERENCES "faction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faction_member" ADD CONSTRAINT "FK_6cc8b2ec024082d725ab16304d8" FOREIGN KEY ("charachter_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faction_member" ADD CONSTRAINT "FK_6069a276a187dfee8f130471a91" FOREIGN KEY ("faction_id") REFERENCES "faction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faction_member" ADD CONSTRAINT "FK_147103591cb8c40c01b99e67870" FOREIGN KEY ("rank_id") REFERENCES "faction_rank"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "court_worker" ADD CONSTRAINT "FK_9073282223b204c83ec2393dbbf" FOREIGN KEY ("character_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "court_worker" ADD CONSTRAINT "FK_2e6b95006fec5d7b39cebbaba89" FOREIGN KEY ("problemsId") REFERENCES "problem"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problem" ADD CONSTRAINT "FK_9cdfb9682c1ffc799a3ef3b13b9" FOREIGN KEY ("creator_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problem" ADD CONSTRAINT "FK_968a17aebdaa2f83ca3ff777f4b" FOREIGN KEY ("court_worker_id") REFERENCES "court_worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problem" ADD CONSTRAINT "FK_9c6e6c677067c6898b0a376358e" FOREIGN KEY ("submission_id") REFERENCES "submission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plant" ADD CONSTRAINT "FK_de6102dd5f4419b65607802ae89" FOREIGN KEY ("price_id") REFERENCES "money"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "garden" ADD CONSTRAINT "FK_d2d6f65a602399f8c176dd4b610" FOREIGN KEY ("pot_1") REFERENCES "pot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "garden" ADD CONSTRAINT "FK_a9c52f99fd00fcb0522fa4e2722" FOREIGN KEY ("pot_2") REFERENCES "pot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "garden" ADD CONSTRAINT "FK_525a4a026064dd97d6c6771c3ee" FOREIGN KEY ("pot_3") REFERENCES "pot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "garden" ADD CONSTRAINT "FK_228e040a77b3ef25e8cc6ca69c5" FOREIGN KEY ("pot_4") REFERENCES "pot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "garden" ADD CONSTRAINT "FK_b065c7e8306df54e5d68f7a4899" FOREIGN KEY ("pot_5") REFERENCES "pot"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drink" ADD CONSTRAINT "FK_3005223ba91709f26b9e6e347ae" FOREIGN KEY ("price_id") REFERENCES "money"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drink" ADD CONSTRAINT "FK_7f0f1e87d014b4b627ce6dfe890" FOREIGN KEY ("drink_id") REFERENCES "drink_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_category" ADD CONSTRAINT "FK_97f8cf61daf55820a4dd514f312" FOREIGN KEY ("parentId") REFERENCES "item_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equpment_item" ADD CONSTRAINT "FK_7a072df0de8b4c9fd479842ef95" FOREIGN KEY ("caterogry_id") REFERENCES "item_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment" ADD CONSTRAINT "FK_07374c077af07d2795c2eb3b88a" FOREIGN KEY ("armor_id") REFERENCES "equpment_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment" ADD CONSTRAINT "FK_de14170221deb328d30d78a3775" FOREIGN KEY ("cloak_id") REFERENCES "equpment_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment" ADD CONSTRAINT "FK_a5f321d7010ff4d4dad3ce48065" FOREIGN KEY ("left_hand_id") REFERENCES "equpment_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment" ADD CONSTRAINT "FK_e735e2987b4d7cd48b9fdc09542" FOREIGN KEY ("right_hand_id") REFERENCES "equpment_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment" ADD CONSTRAINT "FK_50b7d984bf278d5b1957e87f516" FOREIGN KEY ("gloves_id") REFERENCES "equpment_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment" ADD CONSTRAINT "FK_fbbd94225e1292b442e352d8209" FOREIGN KEY ("shoes_id") REFERENCES "equpment_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment" ADD CONSTRAINT "FK_8afb00abb0da8ce7037bb509022" FOREIGN KEY ("ring_id") REFERENCES "equpment_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "equipment" ADD CONSTRAINT "FK_61667b05c492f7f5db0b52bc3b4" FOREIGN KEY ("vehicle_id") REFERENCES "equpment_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_55d96be2679a079fb92a8c3238b" FOREIGN KEY ("background_id") REFERENCES "background"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_70fabaf90fc01eea3796b9b3ce2" FOREIGN KEY ("characteristics_id") REFERENCES "сharacter_сharacteristics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_0d02288a8b2bc07298f21af0a5f" FOREIGN KEY ("grimoire_id") REFERENCES "grimoire"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_523d22374b8851fe6e1a3c574c5" FOREIGN KEY ("inventory_id") REFERENCES "inventory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_4afeeea248417ce2474b06820d9" FOREIGN KEY ("equipment_id") REFERENCES "equipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_3c72e1541fe3bb8c837daa7ecfc" FOREIGN KEY ("wallet_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_213c1fb65c9f528cc11393f2edb" FOREIGN KEY ("user_id") REFERENCES "game_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "character" ADD CONSTRAINT "FK_aa0421a683f4459e9ed104fa971" FOREIGN KEY ("garden_id") REFERENCES "garden"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_account" ADD CONSTRAINT "FK_24569b6843af6bcef189740e99e" FOREIGN KEY ("bank_id") REFERENCES "bank"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problem_judge_info" ADD CONSTRAINT "FK_86e8539b96ed22ce70416416b1e" FOREIGN KEY ("problemId") REFERENCES "problem"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shop" ADD CONSTRAINT "FK_45ef796043f3b27975c32d94d20" FOREIGN KEY ("item_id") REFERENCES "equipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "market" ADD CONSTRAINT "FK_459d9cecb1ca31461755460b4c5" FOREIGN KEY ("owner_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "market" ADD CONSTRAINT "FK_fc9f91dbb8a0d0675d00d292471" FOREIGN KEY ("item_id") REFERENCES "equipment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grimoire_worker" ADD CONSTRAINT "FK_118a283f4407541e0f68e31e75a" FOREIGN KEY ("character_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devil_union" ADD CONSTRAINT "FK_52aec65a8a2bd6aaa314b489a21" FOREIGN KEY ("devil_id") REFERENCES "devils"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devil_union" ADD CONSTRAINT "FK_ea32ff921afa217b45f7ade20f1" FOREIGN KEY ("character_id") REFERENCES "character"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devil_default_spells" ADD CONSTRAINT "FK_929c58456251556b2095ff58d9b" FOREIGN KEY ("devil_id") REFERENCES "devils"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "devil_default_spells" ADD CONSTRAINT "FK_d6a340361d8857cbf4ba12e2f37" FOREIGN KEY ("spell_id") REFERENCES "spell"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill" ADD CONSTRAINT "FK_050ba8921bff2965456d92b2ce9" FOREIGN KEY ("ability_id") REFERENCES "ability"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill" ADD CONSTRAINT "FK_0e6b09300470b12bdaa2dc53372" FOREIGN KEY ("proficiency_id") REFERENCES "proficiency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passive_skill" ADD CONSTRAINT "FK_b1ff57d98655574c868bdf823d0" FOREIGN KEY ("skill_id") REFERENCES "skill"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cat_friends_cat" ADD CONSTRAINT "FK_ba407ac9e21d01a6ba443c27d67" FOREIGN KEY ("catId_1") REFERENCES "cat"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cat_friends_cat" ADD CONSTRAINT "FK_467ed799a40f2b816bf6a8f5246" FOREIGN KEY ("catId_2") REFERENCES "cat"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_eqipment_items" ADD CONSTRAINT "FK_c5cb420e037ea92202f6035d293" FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_eqipment_items" ADD CONSTRAINT "FK_e64ac9b2a96181f165282cba41c" FOREIGN KEY ("equpmentItemId") REFERENCES "equpment_item"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_drinks" ADD CONSTRAINT "FK_668ae9dbce0ac1d5e4600571ece" FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_drinks" ADD CONSTRAINT "FK_92faac90704a9f121d856bf5b7c" FOREIGN KEY ("drinkId") REFERENCES "drink"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "intentory_toolkit" ADD CONSTRAINT "FK_7b1362fffb9935858d2a66ff0d7" FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "intentory_toolkit" ADD CONSTRAINT "FK_ef48b38b9220433b6973d9da711" FOREIGN KEY ("toolKitId") REFERENCES "toolKit"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_gears" ADD CONSTRAINT "FK_54d776e18dc8ee012d50c7eedf9" FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_gears" ADD CONSTRAINT "FK_50175581d42a794ce4b6d3a21e9" FOREIGN KEY ("gearId") REFERENCES "gear"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_vehicles" ADD CONSTRAINT "FK_a55065581d1648dc7aad2734092" FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "inventory_vehicles" ADD CONSTRAINT "FK_a5f68ebe32de2fbb7cb0ebc1e78" FOREIGN KEY ("vehicleId") REFERENCES "vehicle"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "inventory_vehicles" DROP CONSTRAINT "FK_a5f68ebe32de2fbb7cb0ebc1e78"`);
        await queryRunner.query(`ALTER TABLE "inventory_vehicles" DROP CONSTRAINT "FK_a55065581d1648dc7aad2734092"`);
        await queryRunner.query(`ALTER TABLE "inventory_gears" DROP CONSTRAINT "FK_50175581d42a794ce4b6d3a21e9"`);
        await queryRunner.query(`ALTER TABLE "inventory_gears" DROP CONSTRAINT "FK_54d776e18dc8ee012d50c7eedf9"`);
        await queryRunner.query(`ALTER TABLE "intentory_toolkit" DROP CONSTRAINT "FK_ef48b38b9220433b6973d9da711"`);
        await queryRunner.query(`ALTER TABLE "intentory_toolkit" DROP CONSTRAINT "FK_7b1362fffb9935858d2a66ff0d7"`);
        await queryRunner.query(`ALTER TABLE "inventory_drinks" DROP CONSTRAINT "FK_92faac90704a9f121d856bf5b7c"`);
        await queryRunner.query(`ALTER TABLE "inventory_drinks" DROP CONSTRAINT "FK_668ae9dbce0ac1d5e4600571ece"`);
        await queryRunner.query(`ALTER TABLE "inventory_eqipment_items" DROP CONSTRAINT "FK_e64ac9b2a96181f165282cba41c"`);
        await queryRunner.query(`ALTER TABLE "inventory_eqipment_items" DROP CONSTRAINT "FK_c5cb420e037ea92202f6035d293"`);
        await queryRunner.query(`ALTER TABLE "cat_friends_cat" DROP CONSTRAINT "FK_467ed799a40f2b816bf6a8f5246"`);
        await queryRunner.query(`ALTER TABLE "cat_friends_cat" DROP CONSTRAINT "FK_ba407ac9e21d01a6ba443c27d67"`);
        await queryRunner.query(`ALTER TABLE "passive_skill" DROP CONSTRAINT "FK_b1ff57d98655574c868bdf823d0"`);
        await queryRunner.query(`ALTER TABLE "skill" DROP CONSTRAINT "FK_0e6b09300470b12bdaa2dc53372"`);
        await queryRunner.query(`ALTER TABLE "skill" DROP CONSTRAINT "FK_050ba8921bff2965456d92b2ce9"`);
        await queryRunner.query(`ALTER TABLE "devil_default_spells" DROP CONSTRAINT "FK_d6a340361d8857cbf4ba12e2f37"`);
        await queryRunner.query(`ALTER TABLE "devil_default_spells" DROP CONSTRAINT "FK_929c58456251556b2095ff58d9b"`);
        await queryRunner.query(`ALTER TABLE "devil_union" DROP CONSTRAINT "FK_ea32ff921afa217b45f7ade20f1"`);
        await queryRunner.query(`ALTER TABLE "devil_union" DROP CONSTRAINT "FK_52aec65a8a2bd6aaa314b489a21"`);
        await queryRunner.query(`ALTER TABLE "grimoire_worker" DROP CONSTRAINT "FK_118a283f4407541e0f68e31e75a"`);
        await queryRunner.query(`ALTER TABLE "market" DROP CONSTRAINT "FK_fc9f91dbb8a0d0675d00d292471"`);
        await queryRunner.query(`ALTER TABLE "market" DROP CONSTRAINT "FK_459d9cecb1ca31461755460b4c5"`);
        await queryRunner.query(`ALTER TABLE "shop" DROP CONSTRAINT "FK_45ef796043f3b27975c32d94d20"`);
        await queryRunner.query(`ALTER TABLE "problem_judge_info" DROP CONSTRAINT "FK_86e8539b96ed22ce70416416b1e"`);
        await queryRunner.query(`ALTER TABLE "bank_account" DROP CONSTRAINT "FK_24569b6843af6bcef189740e99e"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_aa0421a683f4459e9ed104fa971"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_213c1fb65c9f528cc11393f2edb"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_3c72e1541fe3bb8c837daa7ecfc"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_4afeeea248417ce2474b06820d9"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_523d22374b8851fe6e1a3c574c5"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_0d02288a8b2bc07298f21af0a5f"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_70fabaf90fc01eea3796b9b3ce2"`);
        await queryRunner.query(`ALTER TABLE "character" DROP CONSTRAINT "FK_55d96be2679a079fb92a8c3238b"`);
        await queryRunner.query(`ALTER TABLE "equipment" DROP CONSTRAINT "FK_61667b05c492f7f5db0b52bc3b4"`);
        await queryRunner.query(`ALTER TABLE "equipment" DROP CONSTRAINT "FK_8afb00abb0da8ce7037bb509022"`);
        await queryRunner.query(`ALTER TABLE "equipment" DROP CONSTRAINT "FK_fbbd94225e1292b442e352d8209"`);
        await queryRunner.query(`ALTER TABLE "equipment" DROP CONSTRAINT "FK_50b7d984bf278d5b1957e87f516"`);
        await queryRunner.query(`ALTER TABLE "equipment" DROP CONSTRAINT "FK_e735e2987b4d7cd48b9fdc09542"`);
        await queryRunner.query(`ALTER TABLE "equipment" DROP CONSTRAINT "FK_a5f321d7010ff4d4dad3ce48065"`);
        await queryRunner.query(`ALTER TABLE "equipment" DROP CONSTRAINT "FK_de14170221deb328d30d78a3775"`);
        await queryRunner.query(`ALTER TABLE "equipment" DROP CONSTRAINT "FK_07374c077af07d2795c2eb3b88a"`);
        await queryRunner.query(`ALTER TABLE "equpment_item" DROP CONSTRAINT "FK_7a072df0de8b4c9fd479842ef95"`);
        await queryRunner.query(`ALTER TABLE "item_category" DROP CONSTRAINT "FK_97f8cf61daf55820a4dd514f312"`);
        await queryRunner.query(`ALTER TABLE "drink" DROP CONSTRAINT "FK_7f0f1e87d014b4b627ce6dfe890"`);
        await queryRunner.query(`ALTER TABLE "drink" DROP CONSTRAINT "FK_3005223ba91709f26b9e6e347ae"`);
        await queryRunner.query(`ALTER TABLE "garden" DROP CONSTRAINT "FK_b065c7e8306df54e5d68f7a4899"`);
        await queryRunner.query(`ALTER TABLE "garden" DROP CONSTRAINT "FK_228e040a77b3ef25e8cc6ca69c5"`);
        await queryRunner.query(`ALTER TABLE "garden" DROP CONSTRAINT "FK_525a4a026064dd97d6c6771c3ee"`);
        await queryRunner.query(`ALTER TABLE "garden" DROP CONSTRAINT "FK_a9c52f99fd00fcb0522fa4e2722"`);
        await queryRunner.query(`ALTER TABLE "garden" DROP CONSTRAINT "FK_d2d6f65a602399f8c176dd4b610"`);
        await queryRunner.query(`ALTER TABLE "plant" DROP CONSTRAINT "FK_de6102dd5f4419b65607802ae89"`);
        await queryRunner.query(`ALTER TABLE "problem" DROP CONSTRAINT "FK_9c6e6c677067c6898b0a376358e"`);
        await queryRunner.query(`ALTER TABLE "problem" DROP CONSTRAINT "FK_968a17aebdaa2f83ca3ff777f4b"`);
        await queryRunner.query(`ALTER TABLE "problem" DROP CONSTRAINT "FK_9cdfb9682c1ffc799a3ef3b13b9"`);
        await queryRunner.query(`ALTER TABLE "court_worker" DROP CONSTRAINT "FK_2e6b95006fec5d7b39cebbaba89"`);
        await queryRunner.query(`ALTER TABLE "court_worker" DROP CONSTRAINT "FK_9073282223b204c83ec2393dbbf"`);
        await queryRunner.query(`ALTER TABLE "faction_member" DROP CONSTRAINT "FK_147103591cb8c40c01b99e67870"`);
        await queryRunner.query(`ALTER TABLE "faction_member" DROP CONSTRAINT "FK_6069a276a187dfee8f130471a91"`);
        await queryRunner.query(`ALTER TABLE "faction_member" DROP CONSTRAINT "FK_6cc8b2ec024082d725ab16304d8"`);
        await queryRunner.query(`ALTER TABLE "gang_zone" DROP CONSTRAINT "FK_a2816f8d6dbb4c761d7817dcbaa"`);
        await queryRunner.query(`ALTER TABLE "note" DROP CONSTRAINT "FK_9784437ac65ceb4557307cfdc8a"`);
        await queryRunner.query(`ALTER TABLE "spell" DROP CONSTRAINT "FK_1e2393cb4b4223f42e4e91d91dc"`);
        await queryRunner.query(`ALTER TABLE "spell" DROP CONSTRAINT "FK_e46b14dba921885159dfca2671b"`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" DROP CONSTRAINT "FK_d60a5a2c749df61c88346e60968"`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" DROP CONSTRAINT "FK_e755b69e23f6f408b4dd3a8c162"`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" DROP CONSTRAINT "FK_3ff92766c0608a72fad9bcd4fc2"`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" DROP CONSTRAINT "FK_bec0cf5cc8f25e02155802a1ff6"`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" DROP CONSTRAINT "FK_20cdb54b7dc2dfc3b1608d92729"`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" DROP CONSTRAINT "FK_2266566630597e725171d7d1490"`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" DROP CONSTRAINT "FK_a33571e93e431bf7954a7258103"`);
        await queryRunner.query(`ALTER TABLE "сharacter_сharacteristics" DROP CONSTRAINT "FK_3de7660ddbb03266bf3b45f46bb"`);
        await queryRunner.query(`ALTER TABLE "speed" DROP CONSTRAINT "FK_91b47d4fcf2aa79c2032c8059f8"`);
        await queryRunner.query(`ALTER TABLE "background" DROP CONSTRAINT "FK_65d9c4a0ed73462a9f923546192"`);
        await queryRunner.query(`ALTER TABLE "background" DROP CONSTRAINT "FK_5d6f6589e1b7d72329c7810f39c"`);
        await queryRunner.query(`ALTER TABLE "state" DROP CONSTRAINT "FK_9e79bcb4b9c77c2862cffc0eb10"`);
        await queryRunner.query(`ALTER TABLE "armer_forces" DROP CONSTRAINT "FK_7cba12869189b72b04204c4f741"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_request" DROP CONSTRAINT "FK_a26eb5106444922468f2c4c4470"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_request" DROP CONSTRAINT "FK_0d66a57cc15bb9ac71b799646eb"`);
        await queryRunner.query(`ALTER TABLE "squads" DROP CONSTRAINT "FK_b6692363007ff4724ef82dd1fbf"`);
        await queryRunner.query(`ALTER TABLE "squad_postitions" DROP CONSTRAINT "FK_99c3c43a3481a22d94d21a6af0d"`);
        await queryRunner.query(`ALTER TABLE "squad_postitions" DROP CONSTRAINT "FK_b77c861cd7007de6f9a9cafb7f1"`);
        await queryRunner.query(`ALTER TABLE "squad_postitions" DROP CONSTRAINT "FK_231556cd2d6d9e74640d7a635f4"`);
        await queryRunner.query(`ALTER TABLE "squad_member" DROP CONSTRAINT "FK_e9cfaaedfe354d73610ffa47f07"`);
        await queryRunner.query(`ALTER TABLE "squad_member" DROP CONSTRAINT "FK_6dceec6ada0c6475b462b9fac2a"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_member" DROP CONSTRAINT "FK_039f9946eb75f071be7fc30e24f"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_member" DROP CONSTRAINT "FK_6ec70ac1d854909296159b38efb"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_member" DROP CONSTRAINT "FK_92f902273784e2eb77cb64a70f5"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_member" DROP CONSTRAINT "FK_cc2cf86f1190c133290a824d70c"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_job" DROP CONSTRAINT "FK_7950c11cbb3dc71f364fc69144a"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_rank" DROP CONSTRAINT "FK_775d68267d8bddf6a43dc2f9527"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_rank" DROP CONSTRAINT "FK_49f6578e9d32e203ff8bdbeba17"`);
        await queryRunner.query(`ALTER TABLE "armed_forces_rank" DROP CONSTRAINT "FK_888b47b15df118f71e419c68419"`);
        await queryRunner.query(`ALTER TABLE "province" DROP CONSTRAINT "FK_7100060d132705fe129ff576026"`);
        await queryRunner.query(`ALTER TABLE "province" DROP CONSTRAINT "FK_51b3ecc6d0fd9eb342ee8742274"`);
        await queryRunner.query(`ALTER TABLE "burg" DROP CONSTRAINT "FK_d51177135257fdd6c86a4262104"`);
        await queryRunner.query(`ALTER TABLE "cat_home_pillow_entity" DROP CONSTRAINT "FK_62cf9d1690964fb54245eba4872"`);
        await queryRunner.query(`ALTER TABLE "cat" DROP CONSTRAINT "FK_97f120ed85f1eca4908bc4543c6"`);
        await queryRunner.query(`ALTER TABLE "cat_toy_entity" DROP CONSTRAINT "FK_441e45eec97723bb12d5123213a"`);
        await queryRunner.query(`ALTER TABLE "cat_toy_entity" DROP CONSTRAINT "FK_d8f463fc68814dfd051a9680361"`);
        await queryRunner.query(`ALTER TABLE "toy_shop_entity" DROP CONSTRAINT "FK_bced0fab98307df5ba79db4b34a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5f68ebe32de2fbb7cb0ebc1e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a55065581d1648dc7aad273409"`);
        await queryRunner.query(`DROP TABLE "inventory_vehicles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50175581d42a794ce4b6d3a21e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54d776e18dc8ee012d50c7eedf"`);
        await queryRunner.query(`DROP TABLE "inventory_gears"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef48b38b9220433b6973d9da71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b1362fffb9935858d2a66ff0d"`);
        await queryRunner.query(`DROP TABLE "intentory_toolkit"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92faac90704a9f121d856bf5b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_668ae9dbce0ac1d5e4600571ec"`);
        await queryRunner.query(`DROP TABLE "inventory_drinks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e64ac9b2a96181f165282cba41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5cb420e037ea92202f6035d29"`);
        await queryRunner.query(`DROP TABLE "inventory_eqipment_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_467ed799a40f2b816bf6a8f524"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba407ac9e21d01a6ba443c27d6"`);
        await queryRunner.query(`DROP TABLE "cat_friends_cat"`);
        await queryRunner.query(`DROP TABLE "passive_skill"`);
        await queryRunner.query(`DROP TABLE "skill"`);
        await queryRunner.query(`DROP TYPE "public"."skill_skillproficiency_enum"`);
        await queryRunner.query(`DROP TABLE "food_component"`);
        await queryRunner.query(`DROP TABLE "devil_default_spells"`);
        await queryRunner.query(`DROP TYPE "public"."devil_default_spells_percent_enum"`);
        await queryRunner.query(`DROP TABLE "devil_union"`);
        await queryRunner.query(`DROP TYPE "public"."devil_union_currentpercent_enum"`);
        await queryRunner.query(`DROP TYPE "public"."devil_union_maxavailablepercent_enum"`);
        await queryRunner.query(`DROP TABLE "devils"`);
        await queryRunner.query(`DROP TYPE "public"."devils_rank_enum"`);
        await queryRunner.query(`DROP TYPE "public"."devils_floor_enum"`);
        await queryRunner.query(`DROP TABLE "devil_spell"`);
        await queryRunner.query(`DROP TABLE "announcement"`);
        await queryRunner.query(`DROP TYPE "public"."announcement_type_enum"`);
        await queryRunner.query(`DROP TABLE "grimoire_request"`);
        await queryRunner.query(`DROP TABLE "grimoire_worker"`);
        await queryRunner.query(`DROP TABLE "mana_skin"`);
        await queryRunner.query(`DROP TABLE "mana_zone"`);
        await queryRunner.query(`DROP TABLE "accessory_entity"`);
        await queryRunner.query(`DROP TABLE "boots_entity"`);
        await queryRunner.query(`DROP TABLE "cloak_entity"`);
        await queryRunner.query(`DROP TABLE "clothes"`);
        await queryRunner.query(`DROP TABLE "helmet_entity"`);
        await queryRunner.query(`DROP TABLE "house"`);
        await queryRunner.query(`DROP TABLE "market"`);
        await queryRunner.query(`DROP TABLE "schield_entity"`);
        await queryRunner.query(`DROP TABLE "ring_entity"`);
        await queryRunner.query(`DROP TABLE "necklace_entity"`);
        await queryRunner.query(`DROP TABLE "shop"`);
        await queryRunner.query(`DROP TABLE "weapons"`);
        await queryRunner.query(`DROP TABLE "arrest"`);
        await queryRunner.query(`DROP TABLE "problem_judge_info"`);
        await queryRunner.query(`DROP TABLE "wanted"`);
        await queryRunner.query(`DROP TABLE "mine"`);
        await queryRunner.query(`DROP TABLE "mineral"`);
        await queryRunner.query(`DROP TABLE "money_log"`);
        await queryRunner.query(`DROP TABLE "bank"`);
        await queryRunner.query(`DROP TABLE "bank_account"`);
        await queryRunner.query(`DROP TABLE "spirit"`);
        await queryRunner.query(`DROP TABLE "game_user"`);
        await queryRunner.query(`DROP TYPE "public"."game_user_type_enum"`);
        await queryRunner.query(`DROP TABLE "character"`);
        await queryRunner.query(`DROP TYPE "public"."character_type_enum"`);
        await queryRunner.query(`DROP TABLE "equipment"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "equpment_item"`);
        await queryRunner.query(`DROP TYPE "public"."equpment_item_bodypart_enum"`);
        await queryRunner.query(`DROP TYPE "public"."equpment_item_rarity_enum"`);
        await queryRunner.query(`DROP TABLE "item_category"`);
        await queryRunner.query(`DROP TABLE "drink"`);
        await queryRunner.query(`DROP TABLE "drink_type"`);
        await queryRunner.query(`DROP TABLE "gear"`);
        await queryRunner.query(`DROP TABLE "vehicle"`);
        await queryRunner.query(`DROP TABLE "toolKit"`);
        await queryRunner.query(`DROP TABLE "garden"`);
        await queryRunner.query(`DROP TABLE "pot"`);
        await queryRunner.query(`DROP TABLE "plant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_219b1e601b8b47e38de7f91dbe"`);
        await queryRunner.query(`DROP TABLE "problem"`);
        await queryRunner.query(`DROP TYPE "public"."problem_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebd1b63340ac17250257bb42d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe96352b2f1e9bfb922c54eba1"`);
        await queryRunner.query(`DROP TABLE "submission"`);
        await queryRunner.query(`DROP TABLE "court_worker"`);
        await queryRunner.query(`DROP TABLE "faction_member"`);
        await queryRunner.query(`DROP TABLE "faction"`);
        await queryRunner.query(`DROP TABLE "gang_zone"`);
        await queryRunner.query(`DROP TABLE "faction_rank"`);
        await queryRunner.query(`DROP TABLE "wallet"`);
        await queryRunner.query(`DROP TABLE "note"`);
        await queryRunner.query(`DROP TABLE "grimoire"`);
        await queryRunner.query(`DROP TYPE "public"."grimoire_status_enum"`);
        await queryRunner.query(`DROP TABLE "spell"`);
        await queryRunner.query(`DROP TYPE "public"."spell_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."spell_type_enum"`);
        await queryRunner.query(`DROP TABLE "spell_requirements"`);
        await queryRunner.query(`DROP TABLE "сharacter_сharacteristics"`);
        await queryRunner.query(`DROP TABLE "proficiency"`);
        await queryRunner.query(`DROP TABLE "speed"`);
        await queryRunner.query(`DROP TABLE "armor_class"`);
        await queryRunner.query(`DROP TABLE "armor"`);
        await queryRunner.query(`DROP TABLE "ability"`);
        await queryRunner.query(`DROP TABLE "background"`);
        await queryRunner.query(`DROP TABLE "race"`);
        await queryRunner.query(`DROP TABLE "state"`);
        await queryRunner.query(`DROP TABLE "armer_forces"`);
        await queryRunner.query(`DROP TABLE "armed_forces_request"`);
        await queryRunner.query(`DROP TYPE "public"."armed_forces_request_status_enum"`);
        await queryRunner.query(`DROP TABLE "squads"`);
        await queryRunner.query(`DROP TABLE "squad_postitions"`);
        await queryRunner.query(`DROP TABLE "squad_member"`);
        await queryRunner.query(`DROP TABLE "armed_forces_member"`);
        await queryRunner.query(`DROP TABLE "armed_forces_job"`);
        await queryRunner.query(`DROP TABLE "armed_forces_permission"`);
        await queryRunner.query(`DROP TABLE "armed_forces_rank"`);
        await queryRunner.query(`DROP TABLE "money"`);
        await queryRunner.query(`DROP TABLE "stateform"`);
        await queryRunner.query(`DROP TABLE "province"`);
        await queryRunner.query(`DROP TABLE "province_form"`);
        await queryRunner.query(`DROP TABLE "burg"`);
        await queryRunner.query(`DROP TABLE "cat_hair_entity"`);
        await queryRunner.query(`DROP TABLE "cat_home_entity"`);
        await queryRunner.query(`DROP TABLE "cat_home_pillow_entity"`);
        await queryRunner.query(`DROP TABLE "cat"`);
        await queryRunner.query(`DROP TABLE "cat_toy_entity"`);
        await queryRunner.query(`DROP TABLE "toy_shop_entity"`);
        await queryRunner.query(`DROP TABLE "toy_shop_address_entity"`);
    }

}
