export enum SceneIds {
    entry = 'entry',
    createCharacter = 'create-character',
    createSpell = 'create-spell',
    createSpells = 'create-spells',
    equipment = 'equipment',
    roll = 'foll',
    about = 'about',
    profile = 'profile',
    grimoire = 'grimoire',
    grimoireAdd = 'grimoireAdd',
    grimoireEditName = 'grimoireName',
    grimoireEditColor = 'grimoireColore',
    spells = 'spells',
    inventory = 'inventory',
    wallet = 'wallet',
    work = 'work',
    bio = 'bio',
    characterParameters = 'character-parameters',
    mySpirits = 'my-spirits',
    allSpirits = 'all-spirits',
    allDevils = 'all-devils',
    myDevils = 'my-devils',
    spirits = 'spirits',
    map = 'map',
    squads = 'squad',
    mines = 'mines',
}
